apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{- include "haystack-rag.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.service.nginx.type }}
  ports:
    - port: {{ .Values.service.nginx.port }}
      targetPort: {{ .Values.service.nginx.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-nginx
