apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opensearch-headless
  labels:
    {{- include "haystack-rag.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-opensearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: transport
  selector:
    app: {{ .Release.Name }}-opensearch
