apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "haystack-rag.labels" . | nindent 4 }}
type: Opaque
data:
  opensearch-user: {{ .Values.secrets.opensearchUser | default "admin" | b64enc }}
  opensearch-password: {{ .Values.secrets.opensearchPassword | default "admin" | b64enc }}